/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.pintegradordaisy.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Daisy
 */
public class GuiInstr extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstr
     */
    public GuiInstr() {
        initComponents();
        
    }
    
    public void escuchar (ActionListener controlador) {
    
        btnSalir2.addActionListener(controlador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnS.png"))); // NOI18N
        btnSalir2.setActionCommand("salirInstr");
        btnSalir2.setContentAreaFilled(false);
        getContentPane().add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 790, 320, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Instrucciones.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
