/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.pintegradordaisy.vista;

import ucr.ac.cr.tm2100.g3.pintegradordaisy.controlador.ControladorPrnc;

/**
 *
 * @author Daisy
 */
public class GuiPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal(ControladorPrnc controlador) {
        initComponents();
        escuchar(controlador);
    }
    
    public void escuchar (ControladorPrnc controlador) {
        btnInst.addActionListener(controlador);
        btnJugar.addActionListener(controlador);
        btnSalir.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInst = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnI.png"))); // NOI18N
        btnInst.setActionCommand("instrucciones");
        btnInst.setContentAreaFilled(false);
        getContentPane().add(btnInst, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 360, 110));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnG.png"))); // NOI18N
        btnJugar.setActionCommand("jugar");
        btnJugar.setContentAreaFilled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 340, 110));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnS.png"))); // NOI18N
        btnSalir.setActionCommand("salir");
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, 320, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantallaInicio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInst;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
