/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.pintegradordaisy.vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import ucr.ac.cr.tm2100.g3.pintegradordaisy.modelo.Enemigo;
import ucr.ac.cr.tm2100.g3.pintegradordaisy.modelo.MatrizLab;
import ucr.ac.cr.tm2100.g3.pintegradordaisy.modelo.Personaje;

/**
 *
 * @author Daisy
 */
public class PanelJuego extends javax.swing.JPanel {

    /**
     * Creates new form PanelJuego
     */
    
    private MatrizLab matriz;
    private Personaje personaje;
    private Enemigo enemigo;
    private Image imgpersonaje,imgenemigo;
    private Image camino,pared, agua,fuego, meta;
    
    public PanelJuego() {
        initComponents();
        
        this.personaje=personaje;
        this.enemigo =enemigo;
        this.matriz = new MatrizLab ();
        
        cargarImagenes();
        
    }
    
    private void cargarImagenes(){
        camino = new ImageIcon(getClass().getResource("/img/piso2.png")).getImage();
        pared = new ImageIcon(getClass().getResource("/img/obstaculo2.png")).getImage();
        agua = new ImageIcon(getClass().getResource("/img/Agua.png")).getImage();
        fuego = new ImageIcon(getClass().getResource("/img/Fuego.png")).getImage();
        meta = new ImageIcon(getClass().getResource("/img/meta.png")).getImage();
        imgpersonaje = new ImageIcon(getClass().getResource("/img/personaje.gif")).getImage();
        imgenemigo = new ImageIcon(getClass().getResource("/img/enemigo.gif")).getImage();
    }
    
    public void setPersonaje (Personaje personaje) {
        
        this.personaje = personaje;
    }
    
    public void setEnemigo (Enemigo enemigo) {
        
        this.enemigo = enemigo;
    }
    
     @Override
    protected void paintComponent (Graphics g){
        super.paintComponent(g);
        // La matriz debe existir
        int [][] laberinto = matriz.getlaberinto();
        
        // tamaño celdas
        int size =50;
        
        for (int y =0; y< laberinto.length;y++){
            for (int x = 0; x< laberinto[y].length;x++){
                switch(laberinto[y][x]){
                    case 0:
                        g.drawImage(camino,x* size, y * size,size,size,this);
                        break;
                    case 1:
                        g.drawImage(pared,x* size, y * size,size,size,this);
                        break;
                    case 2:
                        g.drawImage(agua,x* size, y * size,size,size,this);
                        break;
                    case 3:
                        g.drawImage(fuego,x* size, y * size,size,size,this);
                        break;
                    case 4:
                        g.drawImage(meta,x* size, y * size,size,size,this);
                        break;    
                }
            }
        }
        g.drawImage(imgpersonaje, personaje.getPosX(), personaje.getPosY(), this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
